import { Flex } from "@chakra-ui/react";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <Flex justifyContent="center" alignItems="stretch" flexDir="column">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <li>
        <Link href="/user/wallet">user/wallet</Link>
      </li>
      <li>
        <Link href="/admin/dashboard">admin/dashboard</Link>
      </li>
      <li>
        <Link href="/user/mint-site">user/mint-site</Link>
      </li>
    </Flex>
  );
}
