deploy-paymaster:
	forge script script/DeployPaymaster.s.sol --rpc-url https://eth-goerli.g.alchemy.com/v2/OrplVtpzSRR-wgOrhcE6bjbHPu_8ZGui --broadcast -vvvv
deploy-account:
	forge script script/CreateContractAccount.s.sol:CreateContractAccount --rpc-url https://eth-goerli.g.alchemy.com/v2/OrplVtpzSRR-wgOrhcE6bjbHPu_8ZGui --broadcast -vvvv	
deploy-airdrop:
	forge script script/airdropNFTScript.s.sol --rpc-url https://eth-goerli.g.alchemy.com/v2/OrplVtpzSRR-wgOrhcE6bjbHPu_8ZGui --broadcast -vvvv
mint-nft:
	forge script script/MintNFT.s.sol:MintNFTScript --rpc-url https://eth-goerli.g.alchemy.com/v2/OrplVtpzSRR-wgOrhcE6bjbHPu_8ZGui --broadcast -vvvv
deploy-setup:
	forge script script/SetupDaypass.s.sol --rpc-url https://eth-goerli.g.alchemy.com/v2/OrplVtpzSRR-wgOrhcE6bjbHPu_8ZGui --broadcast -vvvv	--etherscan-api-key K14P3TW12QCI2VDR3YIDY7XA9Y5XP2D232 --verify -vvvv